### ISSUE TITLE
Broken key config screen

### ISSUE THREAD

**Issue by crispy-whiskers** [seraxis/lr2oraja-endlessdream#31]
![image](https://github.com/seraxis/lr2oraja-endlessdream/assets/37268337/ef8ad1f1-599a-4c31-81fe-f2e95e94999f)
On LR2oraja, I had my key config fine, but moving over it seems like one of my configs got set to something else. i went to key config to change that, but was greeted with this instead. not sure how to reproduce

**Comment by seraxis** [comment]
This issue is due to a missing `fonts/` folder in your game directory, you can acquire this directory by unzipping the contents of the [0.2.0 release](https://github.com/seraxis/lr2oraja-endlessdream/releases/tag/v0.2.0) or by downloading Beatoraja 0.8.7 and adding any missing directories to your existing install.

If this fixes your problem let me know and I can close the issue

**Comment by seraxis** [comment]
Thanks for pointing this out, unfortunately that's out of my hands and a result of the glfw input library changing over time, I would need more devices personally to be able to write something that smoothly transitions all input devices from main raja to ED that wouldnt have any annoying false positives, so for now rebinding is just part of adopting endless dream
